// Generated by scripts/package_preview_packs.py. Do not edit hashes by hand.
#pragma once

inline constexpr PackFile kMediaPackFiles[] = {
    {L"BUILDCONF.txt", 1030, L"1d416be6139aaefeb3374da5b54c9d09719caf4ae838be144f9a2df208ef33dd", 576, L"a74ed9da8ce76c81477bcf5aefe84b5b42e1e5e283312536d08a1119161ae35b", L"ffmpeg-BUILDCONF.txt.lzms"},
    {L"ffmpeg.exe", 18718208, L"9dcce6f16e496f66e57a16dc3ffb419e4d73a9c92cd9808f270e2d3b7d5266d4", 7405152, L"39bc05bde5b0a2c8ff5e13eadf9593fe0f441364cb3828c3e0b4dbfca5827218", L"ffmpeg-ffmpeg.exe.lzms"},
    {L"ffprobe.exe", 18613248, L"1705bf6910b2b844eb7fda0ffed3966bb8948c517f127fa20a42f244bc597d0d", 7343054, L"5991c0584149835e252789a7f957e0440cd7fb5ef9ff71f162177a877e7a734f", L"ffmpeg-ffprobe.exe.lzms"},
    {L"LICENSE-dav1d.txt", 1317, L"dd92c3c2247c5651606fc23a5e2d6a1ebc5ace9a3e49cbde0e12f05ad1cb1ee5", 916, L"86145eb1e52f41c61d9c50f42b835dac734bb4bae7ab6a6a8b3ee2c308f09a87", L"ffmpeg-LICENSE-dav1d.txt.lzms"},
    {L"LICENSE-FFmpeg-LGPL-2.1.txt", 26526, L"b634ab5640e258563c536e658cad87080553df6f34f62269a21d554844e58bfe", 9710, L"33cc1bc8fcc4a84722997c4b2ba21a6ce7ecdef68cceb51832676c88627dd0f7", L"ffmpeg-LICENSE-FFmpeg-LGPL-2.1.txt.lzms"},
    {L"SOURCE.txt", 296, L"378f77467284a1616bd39c738c06109cdd672c15d4cdcf5821de1e277b4188ce", 288, L"4b13a8ac3d9ca2e1ce792eb3e394e93a1dc83ab0a1a4b5103e68b3a5af11c70e", L"ffmpeg-SOURCE.txt.lzms"},
};
inline constexpr PackRelease kMediaPackRelease{L"ffmpeg", L"1.0.1", L"https://github.com/jimmgreen/pulse/releases/download/v1.0.53/", kMediaPackFiles, std::size(kMediaPackFiles)};

inline constexpr PackFile kImagePackFiles[] = {
    {L"heif.dll", 3281408, L"1d15e773475eb8ce17a4857459fbe196d05961ac6dd391c68a44209179c55831", 1175912, L"fd207a53a598a53bc3932c01b8a86181c6ddfc33528927d320c16bf89b054cac", L"images-heif.dll.lzms"},
    {L"libde265.dll", 536064, L"51d95d4a840ee9c9a82dac808366232ee549e8cd3bd01434f2113a2adc4ec60f", 236436, L"cfa33d3de269a2ab31e4b56f7a640bedc31cd1219ae2fdda1e9d54ff50dafdd8", L"images-libde265.dll.lzms"},
    {L"pulse-imgpack.exe", 3076608, L"58c228ef3e7df48b255b4a71e0e7c87df2307f5de7f0f484a985520c977fd3c0", 1093522, L"04ac2a9b4b435ba82d8ed59c9e7ab5aa3e0175679a142e402dc18e4aca3ccd1e", L"images-pulse-imgpack.exe.lzms"},
    {L"THIRD_PARTY_NOTICES.txt", 122243, L"d16fbac43c0e968769c31df64048f995acd8812307a1acd3e3fa133c7d26811b", 34512, L"91c323a71a6818d32c95f4a4ec70453ce0fde1763dc2efcc02d7ed98f745feb5", L"images-THIRD_PARTY_NOTICES.txt.lzms"},
};
inline constexpr PackRelease kImagePackRelease{L"images", L"1.0.1", L"https://github.com/jimmgreen/pulse/releases/download/v1.0.53/", kImagePackFiles, std::size(kImagePackFiles)};

inline constexpr PackFile kRawPackFiles[] = {
    {L"pulse-rawpack.exe", 173056, L"4eb07ac1684ee7318da5cf1b4c63b4c735c1dde4750306e28760ec8066e88c68", 79038, L"f13e567c9e0cfc99fa4aae87751c46d24fdd1dd080ee3c150efd73e05ee1c86d", L"raw-pulse-rawpack.exe.lzms"},
    {L"raw_r.dll", 2180096, L"d55bb88c6b43f5ed17a001f99b139253a2e2d4cfbff289a30ef1b493a3f79c98", 732750, L"a39c3be4c36199efff1e0b991f2e4d66a009d17080ff7483d2629e8f28cf3fc9", L"raw-raw_r.dll.lzms"},
    {L"THIRD-PARTY-NOTICES.txt", 53926, L"54bed68b3f940a25ffea55679f35973058f5f29c2c5ab77537754adfd0704f82", 17466, L"f056e02cafd33b95e943162fd67ace3931ba09f90e5e6680e1912f738c4bbb09", L"raw-THIRD-PARTY-NOTICES.txt.lzms"},
};
inline constexpr PackRelease kRawPackRelease{L"raw", L"1.0.1", L"https://github.com/jimmgreen/pulse/releases/download/v1.0.53/", kRawPackFiles, std::size(kRawPackFiles)};

inline constexpr PackFile kArchivePackFiles[] = {
    {L"7z.dll", 1908736, L"bbd705e3b58ca7677c1e9e67473f166a6712da034dcb567d571fbb67507a443f", 754450, L"33b256c217edfa5d81cfabe740e7378815cfec36eb79b551d18e083769dbf802", L"archive-7z.dll.lzms"},
    {L"7z.exe", 575488, L"4a41aa37786c7eae7451e81c2c97458d5d1ae5a3a8154637a0d5f77adc05e619", 219174, L"3f42f16ea44ab02ae201e98b11558c91b1e66337872aee2c4a3cc33f5960b259", L"archive-7z.exe.lzms"},
    {L"License.txt", 6031, L"519ac0a4bded9c18ea02e0afb71f663d8c47373bd9facd3ac96a79f51d77765d", 2242, L"911666a80c81363c28106cfac2d09f99b3d7f68eb929a1bfade1ee60387b9cb4", L"archive-License.txt.lzms"},
    {L"NOTICE.txt", 307, L"88a4e61cc4858cb4086acd028b16fea1a76ddd9eabc7b09a8bec7dc3f840eb89", 308, L"7e27daea019f5eb04908489f8759eabd17a8831ada71871cad072d6fbce8e1c5", L"archive-NOTICE.txt.lzms"},
};
inline constexpr PackRelease kArchivePackRelease{L"archive", L"1.0.1", L"https://github.com/jimmgreen/pulse/releases/download/v1.0.53/", kArchivePackFiles, std::size(kArchivePackFiles)};
