"""Stage four packs beside one installer release; never upload anything.

Run on Windows after building the pack directories. The generated catalog is
compiled into Pulse; both compressed and installed bytes are pinned by SHA-256.
"""
import argparse
import ctypes as ct
import hashlib
import json
from pathlib import Path
import re

SYMBOLS = {'ffmpeg': 'Media', 'images': 'Image', 'raw': 'Raw', 'archive': 'Archive'}
TOOLS = {'ffmpeg': 'ffmpeg.exe', 'images': 'pulse-imgpack.exe', 'raw': 'pulse-rawpack.exe', 'archive': '7z.exe'}
MAX_FILE = 256 * 1024 * 1024


def require(ok, message):
    if not ok:
        raise RuntimeError(message)


class Lzms:
    def __init__(self):
        self.api = ct.WinDLL('cabinet', use_last_error=True)
        for name in ('CreateCompressor', 'CreateDecompressor'):
            fn = getattr(self.api, name)
            fn.argtypes = [ct.c_uint, ct.c_void_p, ct.POINTER(ct.c_void_p)]
            fn.restype = ct.c_int
        for name in ('Compress', 'Decompress'):
            fn = getattr(self.api, name)
            fn.argtypes = [ct.c_void_p, ct.c_void_p, ct.c_size_t, ct.c_void_p, ct.c_size_t, ct.POINTER(ct.c_size_t)]
            fn.restype = ct.c_int
        for name in ('CloseCompressor', 'CloseDecompressor'):
            getattr(self.api, name).argtypes = [ct.c_void_p]

    def pack(self, data):
        handle = ct.c_void_p()
        require(self.api.CreateCompressor(5, None, ct.byref(handle)), 'CreateCompressor failed')
        try:
            source = ct.create_string_buffer(data)
            needed = ct.c_size_t()
            self.api.Compress(handle, source, len(data), None, 0, ct.byref(needed))
            require(0 < needed.value <= MAX_FILE, 'Invalid compressed size')
            buffer = ct.create_string_buffer(needed.value)
            require(self.api.Compress(handle, source, len(data), buffer, len(buffer), ct.byref(needed)), 'Compress failed')
            packed = buffer.raw[:needed.value]
        finally:
            self.api.CloseCompressor(handle)
        require(self.api.CreateDecompressor(5, None, ct.byref(handle)), 'CreateDecompressor failed')
        try:
            source = ct.create_string_buffer(packed)
            buffer = ct.create_string_buffer(len(data))
            written = ct.c_size_t()
            require(self.api.Decompress(handle, source, len(packed), buffer, len(data), ct.byref(written)), 'Decompress failed')
            require(written.value == len(data) and buffer.raw == data, 'LZMS round-trip mismatch')
        finally:
            self.api.CloseDecompressor(handle)
        return packed


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--tag', required=True)
    parser.add_argument('--version', required=True)
    parser.add_argument('--output', type=Path, required=True)
    parser.add_argument('--catalog', type=Path, required=True)
    parser.add_argument('--pack', action='append', required=True, help='key=pack-directory; provide all four keys')
    args = parser.parse_args()
    for value in (args.tag, args.version):
        require(re.fullmatch(r'[A-Za-z0-9][A-Za-z0-9_.-]*', value), 'Invalid release tag/version')
    packs = {}
    for item in args.pack:
        key, directory = item.split('=', 1)
        require(key in SYMBOLS and key not in packs, 'Unknown/duplicate pack key')
        packs[key] = Path(directory).resolve(strict=True)
    require(set(packs) == set(SYMBOLS), 'All four pack directories are required')
    for key, directory in packs.items():
        require((directory / TOOLS[key]).is_file(), f'Missing main tool: {key}')
    args.output.mkdir(parents=True, exist_ok=True)
    codec = Lzms()
    lines = ['// Generated by scripts/package_preview_packs.py. Do not edit hashes by hand.', '#pragma once', '']
    base = f'https://github.com/jimmgreen/pulse/releases/download/{args.tag}/'
    release_files = []
    for key in SYMBOLS:
        symbol = SYMBOLS[key]
        files = []
        lines.append(f'inline constexpr PackFile k{symbol}PackFiles[] = {{')
        for path in sorted(packs[key].iterdir()):
            require(path.is_file() and re.fullmatch(r'[A-Za-z0-9_.-]+', path.name), f'Unexpected pack entry: {path.name}')
            require(0 < path.stat().st_size <= MAX_FILE, f'Invalid file size: {path.name}')
            data = path.read_bytes()
            packed = codec.pack(data)
            name = f'{key}-{path.name}.lzms'
            (args.output / name).write_bytes(packed)
            digest = hashlib.sha256(data).hexdigest()
            packed_hash = hashlib.sha256(packed).hexdigest()
            files.append(dict(name=path.name, size=len(data), sha256=digest, packed_size=len(packed), packed_sha256=packed_hash, download_name=name))
            lines.append(f'    {{L"{path.name}", {len(data)}, L"{digest}", {len(packed)}, L"{packed_hash}", L"{name}"}},')
            release_files.append(dict(name=name, size=len(packed), sha256=packed_hash))
        lines += ['};', f'inline constexpr PackRelease k{symbol}PackRelease{{L"{key}", L"{args.version}", L"{base}", k{symbol}PackFiles, std::size(k{symbol}PackFiles)}};', '']
        manifest_name = f'pulse-pack-{key}-{args.version}.json'
        manifest = dict(id=key, version=args.version, release_tag=args.tag, files=files)
        (args.output / manifest_name).write_text(json.dumps(manifest, indent=2) + '\n', encoding='utf-8')
        print(f'{key}: {len(files)} verified files, {sum(f["packed_size"] for f in files)} download bytes')
    args.catalog.parent.mkdir(parents=True, exist_ok=True)
    args.catalog.write_text('\n'.join(lines), encoding='utf-8')
    (args.output / 'preview-packs-assets.json').write_text(json.dumps(dict(release_tag=args.tag, assets=release_files), indent=2) + '\n', encoding='utf-8')


if __name__ == '__main__':
    main()
